//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaCagriMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmanTb
    {
        public int Id { get; set; }
        public Nullable<int> DepartmanId { get; set; }
        public string DepartmanAdi { get; set; }
        public string Sorumlu { get; set; }
        public Nullable<int> PersonelSayisi { get; set; }
    }
}
