//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaCagriMvc.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FabrikaDbEntities : DbContext
    {
        public FabrikaDbEntities()
            : base("name=FabrikaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTb> AdminTb { get; set; }
        public virtual DbSet<CagriTb> CagriTb { get; set; }
        public virtual DbSet<DepartmanTb> DepartmanTb { get; set; }
        public virtual DbSet<GorevDetayTb> GorevDetayTb { get; set; }
        public virtual DbSet<GorevTb> GorevTb { get; set; }
        public virtual DbSet<MusteriTb> MusteriTb { get; set; }
        public virtual DbSet<CagriDetayTb> CagriDetayTb { get; set; }
        public virtual DbSet<MesajlarTb> MesajlarTb { get; set; }
        public virtual DbSet<PersonelBilgileriTb> PersonelBilgileriTb { get; set; }
    }
}
