//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaCagriMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriTb()
        {
            this.CagriTb = new HashSet<CagriTb>();
            this.MesajlarTb = new HashSet<MesajlarTb>();
            this.MesajlarTb1 = new HashSet<MesajlarTb>();
        }
    
        public int Id { get; set; }
        public string FirmaAdi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Sektor { get; set; }
        public string il { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string Yetkili { get; set; }
        public string Gorsel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CagriTb> CagriTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajlarTb> MesajlarTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajlarTb> MesajlarTb1 { get; set; }
    }
}
