//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaCagriMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelBilgileriTb
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string Tc { get; set; }
        public string Pozisyon { get; set; }
        public string Adres { get; set; }
        public string Departman { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Yonetici { get; set; }
        public Nullable<int> Ucret { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
